before_script: 
   - cd ./VRL-Incubation-Types/

language: java

jdk:
- oraclejdk7

env:
- TERM=dumb

after_success:
- ./gradlew jacocoTestReport coveralls

notifications:
  email:
    - stephan@syntaktischer-zucker.de
    - markus.breit@gcsc.uni-frankfurt.de
    - michael.hoffer@gcsc.uni-frankfurt.de
  on_success: always
  on_failure: always
